services:
  - type: web
    name: smarttraffic
    runtime: docker
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: 8080
