services:
  - type: web
    name: traffic-violation-app
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
    javaVersion: 21
